### ISSUE TITLE
Image endpoint

### ISSUE THREAD

**Issue by ryanhinkel** [wiota/lime#123]
I am noting some really significant delays when hitting the image endpoint. This seems to happen when a lot of files are requested at once. This is becoming a serious usability issue at times for me. Unfortunately I have no good tools right now to diagnose the problem.

Is this a threading problem?

![screen shot 2015-05-27 at 7 24 06 pm](https://cloud.githubusercontent.com/assets/3329425/7849684/1bea1fa8-04a6-11e5-8372-f4279ff312a1.png)

**Comment by ryanhinkel** [comment]
Note the 206 response.

**Comment by di** [comment]
This is the threading issue I was talking about a few weeks ago.

The 206 is the correct response here, and is coming from S3, not us.

**Comment by ryanhinkel** [comment]
I believe the 206 is the correct response because of this `Range: bytes=0-` in the request headers.

```
GET /Turbulance_1432776111184.m4a HTTP/1.1
Host: lime_8aa135a0b841dd3257c7770af735ddb6.s3.amazonaws.com
Connection: keep-alive
Accept-Encoding: identity;q=1, *;q=0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Accept: */*
Referer: http://lime-dev:5001/
Accept-Language: en-US,en;q=0.8
Range: bytes=0-
```
