### ISSUE TITLE
Display predset (with link(s)) when in work or category view

### ISSUE THREAD

**Issue by di** [wiota/lime#28]
Ideally, this would give the user a way to return to the vertex they navigated to their current position from.

It could be the same as hitting the back button, or it could be a list of all vertices one hop upstream from the current vertex.

**Comment by ryanhinkel** [comment]
This is available in GOD mode as a vertex path, which is the way it should work. There is an issue when refreshing LIME. The history is lost and there is no way to retrace it. When we implement #97 we should be able to revisit this and solve it more elegantly.
