### ISSUE TITLE
PUT to modify Happening apex succset fails

### ISSUE THREAD

**Issue by di** [wiota/lime#94]
This occurs when reordering.

This is because `/api/v1/apex/happenings/succset/` is not an endpoint that exists. What does exist is `/api/v1/<vertex_type>/<id>/succset/` (The vertex_type is not currently being used). We are essentially trying to put the succset of the vertex with _id "happenings" and it fails.

We need to switch to using the `/api/v1/<vertex_type>/<id>/succset/` in all cases. This means that the `/api/v1/apex/body/succset` endpoint will be eliminated as well.

Steps to fix:
1. Change which endpoints we are PUTting to in the frontend (Ryan);
2. Remove the `/apex/body/succset` endpoint in the backend (Dustin).

**Comment by ryanhinkel** [comment]
Step 1 is complete (has been for a while)

**Comment by ryanhinkel** [comment]
Step 2 is as well.
